/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "inverse-primary": "#b7c4ff",
        "primary-fixed-dim": "#b7c4ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "primary-fixed": "#dce1ff",
        "tertiary-fixed": "#bee9ff",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container": "#eaedff",
        "on-primary-fixed": "#001551",
        "on-background": "#131b2e",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a1cde3",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001f2a",
        "secondary-fixed": "#d8e2ff",
        "surface-tint": "#2151da",
        "on-surface": "#131b2e",
        "error": "#ba1a1a",
        "on-primary-container": "#cad3ff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#0058be",
        "secondary-container": "#2170e4",
        "inverse-on-surface": "#eef0ff",
        "on-secondary": "#ffffff",
        "background": "#faf8ff",
        "on-secondary-container": "#fefcff",
        "on-error-container": "#93000a",
        "surface-container-high": "#e2e7ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-container": "#afdbf2",
        "outline": "#747686",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#366175",
        "surface-container-highest": "#dae2fd",
        "outline-variant": "#c4c5d7",
        "primary": "#0037b0",
        "tertiary": "#1b495c",
        "on-primary-fixed-variant": "#0039b5",
        "on-surface-variant": "#434655",
        "on-secondary-fixed": "#001a42",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed-variant": "#1e4c5f",
        "primary-container": "#1d4ed8",
        "surface-variant": "#dae2fd",
        "inverse-surface": "#283044",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out 2s infinite",
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "pulse-soft": "pulseSoft 3s ease-in-out infinite",
        "slide-in-right": "slideInRight 0.5s ease-out forwards",
        "count-up": "countUp 2s ease-out forwards",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
};
