import { GoogleGenerativeAI } from '@google/generative-ai';

let genAI = null;

if (process.env.GEMINI_API_KEY) {
  genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
}

const FALLBACK_MODELS = [
  'gemini-3.1-flash-lite-preview',
  'gemini-2.5-flash-lite',
  'gemma-4-31b-it'
];

let model = {
  generateContent: async (prompt) => {
    if (!genAI) throw new Error('AI_UNAVAILABLE');
    let lastError = null;

    for (const modelName of FALLBACK_MODELS) {
      try {
        const currentModel = genAI.getGenerativeModel({
          model: modelName,
          generationConfig: {
            temperature: 0.2, // low temp for accurate analysis
            responseMimeType: 'application/json' // force JSON output explicitly
          }
        });
        const response = await currentModel.generateContent(prompt);
        return response;
      } catch (error) {
        console.warn(`[Gemini Fallback] Model ${modelName} failed:`, error.message);
        lastError = error;
      }
    }
    throw lastError || new Error('All fallback models failed');
  }
};

/**
 * Perform a deep contextual match of Resume and Job Description
 */
export async function analyzeResumeVsJD(resumeText, jobDescription) {
  if (!model) {
    console.warn('GEMINI_API_KEY not found.');
    throw new Error('AI_UNAVAILABLE');
  }

  try {
    const prompt = `You are an expert ATS (Applicant Tracking System) analyzer.

Carefully analyze this resume against the job description.

=== RESUME ===
${resumeText}

=== JOB DESCRIPTION ===
${jobDescription}

Return ONLY this exact JSON structure, no other text. Strictly adhere to these types and keys:
{
  "overallScore": number,          // 0-100, weighted average
  "breakdown": {
    "keywordMatch": number,        // 0-100, % of JD keywords in resume
    "formatScore": number,         // 0-100, structure and ATS readability
    "sectionCompleteness": number, // 0-100, all sections present and filled
    "readabilityScore": number     // 0-100, clear language, no jargon issues
  },
  "missingKeywords": string[],     // important JD keywords not in resume
  "presentKeywords": string[],     // JD keywords successfully found
  "partialMatches": [              // skills mentioned but need improvement
    { "keyword": string, "issue": string }
  ],
  "suggestions": string[],         // max 5 specific actionable fixes
  "strengths": string[],           // max 3 things resume does well
  "formatIssues": string[]         // structural problems found, or empty array
}`;

    const response = await model.generateContent(prompt);
    const rawContent = response.response.text().trim();
    
    let parsed;
    try {
      parsed = JSON.parse(rawContent);
    } catch (parseErr) {
       console.error('[Gemini JSON Parse Error in ATS Analysis]', parseErr.message, 'Raw response:', rawContent);
       throw new Error(`Invalid JSON generated by Gemini: ${parseErr.message}`);
    }

    return parsed;
  } catch (error) {
    console.error('[Gemini Error - analyzeResumeVsJD]', error.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Generate suggestions on how to tailor a resume specifically for a new JD
 */
export async function tailorResumeForJD(resumeText, jobDescription, currentSkills) {
  if (!model) {
    throw new Error('AI_UNAVAILABLE');
  }

  try {
    const prompt = `You are a professional resume consultant.
The user wants to tailor their resume for this job.

=== CURRENT RESUME ===
${resumeText}

=== TARGET JOB DESCRIPTION ===
${jobDescription}

=== CURRENT SKILLS ===
${currentSkills.join(', ')}

Return ONLY this exact JSON structure:
{
  "newSummary": string,              // rewritten summary for this specific JD
  "skillsToAdd": string[],           // skills from JD user should add if they have them
  "skillsToHighlight": string[],     // existing skills to move to top
  "bulletImprovements": [
    {
      "section": string,             // Experience/Project section name
      "original": string,            // original bullet
      "improved": string,            // rewritten to match JD keywords
      "reason": string               // why this change helps
    }
  ],
  "keywordsToWeave": string[],       // exact phrases to add naturally into resume
  "estimatedScoreAfter": number      // predicted ATS score (0-100) after applying suggestions
}`;

    const response = await model.generateContent(prompt);
    const rawContent = response.response.text().trim();
    
    let parsed;
    try {
      parsed = JSON.parse(rawContent);
    } catch (parseErr) {
       console.error('[Gemini JSON Parse Error in Tailor]', parseErr.message);
       throw new Error(`Invalid JSON generated by Gemini: ${parseErr.message}`);
    }

    return parsed;
  } catch (error) {
    console.error('[Gemini Error - tailorResumeForJD]', error.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Perform deep evaluation of an interview answer
 */
export async function evaluateAnswer(question, questionType, topic, idealAnswerOutline, userAnswer, experienceLevel) {
  if (!model) {
    throw new Error('AI_UNAVAILABLE');
  }
  
  if (!userAnswer || userAnswer.trim().length === 0) {
    throw new Error('ANSWER_TOO_SHORT');
  }

  try {
    const prompt = `You are an expert technical interviewer evaluating a candidate's answer.

Interview context:
- Question Type: ${questionType}
- Topic: ${topic}  
- Experience Level Expected: ${experienceLevel}

Question asked:
${question}

What a good answer should cover:
${idealAnswerOutline}

Candidate's answer:
${userAnswer}

Evaluate this answer deeply and honestly. Be realistic. A perfect 10 means flawless.

Return ONLY this exact JSON structure:
{
  "score": number,                    // 0-10 scale (can use decimals like 6.5)
  "technicalAccuracy": number,        // 0-10
  "communicationClarity": number,     // 0-10
  "depthOfKnowledge": number,         // 0-10
  
  "verdict": "string",                // 'Excellent'|'Good'|'Acceptable'|'Needs Improvement'|'Incorrect'
  
  "strengths": ["string"],            // 2-3 specific things said correctly
  "improvements": ["string"],         // 2-3 specific gaps or mistakes
  
  "missedConcepts": ["string"],       // important concepts not mentioned
  
  "idealAnswer": "string",            // comprehensive ideal answer, 100-200 words
  
  "quickFeedback": "string",          // 1-2 sentence spoken feedback, encouraging but honest (mentor style)
  
  "followUpSuggestion": "string"      // what the interviewer might ask next based on this response
}`;

    const response = await model.generateContent(prompt);
    let rawContent = response.response.text().trim();
    
    // Quick cleanup
    if (rawContent.startsWith('\`\`\`json')) {
      rawContent = rawContent.replace(/^\`\`\`json/, '').replace(/\`\`\`$/, '').trim();
    } else if (rawContent.startsWith('\`\`\`')) {
      rawContent = rawContent.replace(/^\`\`\`/, '').replace(/\`\`\`$/, '').trim();
    }
    
    let parsed;
    try {
      parsed = JSON.parse(rawContent);
    } catch (parseErr) {
       console.error('[Gemini JSON Parse Error in Evaluate]', parseErr.message);
       throw new Error(`Invalid JSON generated by Gemini: ${parseErr.message}`);
    }

    return parsed;
  } catch (error) {
    console.error('[Gemini Error - evaluateAnswer]', error.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

// ─── SKILL GAP ANALYZER FUNCTIONS ──────────────────────────────────────────

/**
 * Clean raw Serper snippets into a structured Job Description
 */
export async function cleanAndStructureJD(rawSnippets, jobTitle, experienceLevel) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `You are a job requirements expert.
Below are raw Google search snippets about '${jobTitle}' role at '${experienceLevel}' level.
Extract and structure the actual skill requirements.

Raw snippets:
${rawSnippets.join('\n---\n')}

Return ONLY this JSON:
{
  "requiredSkills": ["skill1", "skill2"],
  "preferredSkills": ["skill1", "skill2"],
  "toolsAndTech": ["tool1", "tool2"],
  "conceptsAndTheory": ["concept1", "concept2"],
  "cleanedJDSummary": "2-3 sentence summary of the role",
  "allSkillsCombined": ["skill1", "tool1", "etc"]
}`;

  try {
    const result = await model.generateContent(prompt);
    let text = result.response.text();
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();
    return JSON.parse(text);
  } catch (e) {
    console.error('[Gemini Error - cleanAndStructureJD]', e.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Build a company-specific skill profile from snippets
 */
export async function buildCompanySkillProfile(company, role, snippets, sources) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `Build a specific skill requirement profile for ${role} at ${company}.
Use these real data points fetched from the web:
${snippets.join('\n---\n')}

Return ONLY this JSON:
{
  "requiredSkills": ["skill1"],
  "companySpecificFocus": ["focus1"],
  "interviewTopics": ["topic1"],
  "techStack": ["tech1"],
  "difficultyNotes": "Heavy DSA / System Design focused",
  "insiderTips": ["tip1", "tip2", "tip3"],
  "allSkillsCombined": ["skill1", "tech1", "focus1"]
}`;

  try {
    const result = await model.generateContent(prompt);
    let text = result.response.text();
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();
    return JSON.parse(text);
  } catch (e) {
    console.error('[Gemini Error - buildCompanySkillProfile]', e.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Deep analysis of User Skills vs Required Skills
 */
export async function analyzeSkillGap_Gemini(userSkills, requiredSkills, experienceLevel) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `You are an expert career coach analyzing a skill gap.

Candidate's current skills:
${userSkills.join(', ')}

Role requires these skills:
${requiredSkills.join(', ')}

Experience level: ${experienceLevel}

Analyze carefully. Consider partial knowledge (knowing React basics != knowing Advanced React).

Return ONLY this JSON:
{
  "matched": [
    { "skill": "React", "confidence": "full", "note": "Well matched" }
  ],
  "missing": [
    { 
      "skill": "Docker", 
      "priority": "high",
      "reason": "Critical for deployment",
      "estimatedWeeks": 2
    }
  ],
  "gapScore": 65,
  "summaryNote": "Strong in frontend, needs DevOps focus."
}`;

  try {
    const result = await model.generateContent(prompt);
    let text = result.response.text();
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();
    return JSON.parse(text);
  } catch (e) {
    console.error('[Gemini Error - analyzeSkillGap]', e.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Extract skills from raw resume PDF text
 */
export async function extractSkillsFromResumeText(resumeText) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `Extract all technical skills, tools, and technologies from this resume.
Include: programming languages, frameworks, libraries, tools, platforms, databases, methodologies.
Exclude: soft skills, company names, degree names.
Return ONLY a JSON array of strings. Max 50 skills.
Deduplicate. Normalize casing (e.g. React not react).

Resume text:
${resumeText.substring(0, 4000)}`;

  try {
    const result = await model.generateContent(prompt);
    let text = result.response.text();
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();
    const parsed = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    console.error('[Gemini Error - extractSkills]', e.message);
    return []; // Return empty array instead of failing the whole flow
  }
}

/**
 * Generate a personalized roadmap using Gemini
 */
export async function generateRoadmap({ goal, currentLevel, dailyHours, learningStyle, targetDeadline, budget, userSkills, importedMissingSkills, marketTrends }) {
  if (!model) throw new Error("Gemini API not configured");

  const totalWeeksMap = { '1month': 4, '3months': 12, '6months': 24, '1year': 48 };
  const totalWeeks = totalWeeksMap[targetDeadline] || 12;
  const weeklyHours = dailyHours * 7;

  const prompt = `You are an expert career coach and curriculum designer.
Generate a complete week-by-week learning roadmap.

=== USER GOAL ===
${goal}

=== PROFILE ===
Current Level: ${currentLevel}
Already knows: ${userSkills?.join(', ') || 'None'}
Daily study time: ${dailyHours} hours -> ${weeklyHours} hours/week
Learning preference: ${learningStyle}
Target deadline: ${targetDeadline} (${totalWeeks} weeks total)
Budget: ${budget}

=== SKILLS TO INCLUDE (from gap analysis) ===
${importedMissingSkills?.join(', ') || 'None imported — derive from goal'}

=== MARKET TRENDS (prioritize these skills) ===
Trending right now: ${marketTrends?.trendingSkills?.join(', ') || 'None'}
Market context: ${marketTrends?.rawSnippets?.slice(0, 5).join(' | ') || 'None'}

=== GENERATION RULES ===
1. Skip skills in 'already knows' list entirely.
2. Place trending market skills EARLIER in the roadmap.
3. Match ${learningStyle}: 
   video -> suggest video-based activities
   project -> every 2 weeks must have a hands-on project
   reading -> suggest docs + articles
4. Adjust depth to deadline:
   1 month -> critical path only, no extras
   6 months -> full depth + portfolio projects
5. Each week: realistic for ${weeklyHours} hours available.
6. Include a milestone every 3-4 weeks.
7. Final 2 weeks: always 'Portfolio + Job Applications'.

Return ONLY valid JSON (no markdown backticks). Schema:
{
  "title": string,
  "goal": string,
  "totalWeeks": number,
  "weeklyHours": number,
  "marketInfluenced": [string],
  "weeks": [
    {
      "weekNumber": number,
      "title": string,
      "topics": [
        {
          "name": string,
          "description": string,
          "estimatedHours": number,
          "resourceHint": string
        }
      ],
      "weeklyProject": string | null,
      "milestone": string | null,
      "estimatedTotalHours": number
    }
  ],
  "finalOutcome": string,
  "portfolioProjects": [string]
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    const cleanText = text.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(cleanText);
  } catch (error) {
    console.error('[Gemini Roadmap Error]', error);
    throw error;
  }
}

/**
 * Regenerate roadmap when a user falls behind
 */
export async function regenerateRoadmap({ originalGoal, completedWeeks, remainingWeeks, weeksDelayed, dailyHours, originalDeadline }) {
  if (!model) throw new Error("Gemini API not configured");

  const prompt = `The user is behind on their learning roadmap. Re-plan the remaining weeks.

Original goal: ${originalGoal}
Weeks completed: ${completedWeeks.length}
Weeks behind schedule: ${weeksDelayed}
Remaining time available: ${remainingWeeks.length - weeksDelayed} weeks
Daily hours available: ${dailyHours}

Completed topics:
${completedWeeks.map(w => w.title).join(', ')}

Remaining original plan:
${JSON.stringify(remainingWeeks)}

Re-planning rules:
1. MUST-HAVE topics: Keep in compressed form.
2. NICE-TO-HAVE topics: Move to 'optional' or remove.
3. Combine related topics into single weeks where possible.
4. Keep all milestones — just adjust which week they fall on.
5. Add a note per compressed week: "This was originally 2 weeks".
6. Final 2 weeks still: Portfolio + Applications.

Return ONLY valid JSON (no markdown backticks) for the REMAINING weeks (renumber from current week + 1).
Array of Week objects Schema:
[
  {
    "weekNumber": number,
    "title": string,
    "topics": [
      {
        "name": string,
        "description": string,
        "estimatedHours": number,
        "resourceHint": string
      }
    ],
    "weeklyProject": string | null,
    "milestone": string | null,
    "estimatedTotalHours": number,
    "replanningNote": string
  }
]`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    const cleanText = text.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    const parsed = JSON.parse(cleanText);
    return Array.isArray(parsed) ? parsed : (parsed.weeks || []);
  } catch (error) {
    console.error('[Gemini Roadmap Regen Error]', error);
    throw error;
  }
}

/**
 * GROUNDING: Uses gemini-2.5-flash with Google Search + Exa context
 * to generate verified quick facts about a company.
 */
export async function groundedCompanyFacts(company, role, exaData) {
  if (!process.env.GEMINI_API_KEY) {
    return { companySize: "", founded: "", headquarters: "", industry: "", interviewRounds: 0, avgTimelineWeeks: 0, difficulty: "", glassdoorRating: 0, latestNews: [], techStackHighlights: [], freshersCtcRange: "", midLevelCtcRange: "", seniorCtcRange: "", joiningBonus: "", stockOptions: "" };
  }

  // Use full Flash model for grounding capability
  const groundingGenAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const groundedModel = groundingGenAI.getGenerativeModel({
    model: 'gemini-2.5-flash',
    tools: [{ googleSearch: {} }] // Enable built-in search
  });

  const prompt = `Research ${company} for a candidate preparing for a ${role} interview.

I already have this data from the web — use it as context:

INTERVIEW EXPERIENCES:
${exaData.interviewExperiences.map(r => r.highlights.join(' ')).join('\\n')}

SALARY DATA:
${exaData.salaryData.map(r => r.highlights.join(' ')).join('\\n')}

CULTURE REVIEWS:
${exaData.cultureReviews.map(r => r.highlights.join(' ')).join('\\n')}

Using this context AND your Google Search capability,
provide these specific facts about ${company}:

Return ONLY this JSON (do not use markdown backticks):
{
  "companySize": "string",
  "founded": "string",
  "headquarters": "string",
  "industry": "string",
  "interviewRounds": 0,
  "avgTimelineWeeks": 0,
  "difficulty": "string",
  "glassdoorRating": 0,
  "latestNews": [
    { "headline": "string", "date": "string", "source": "string" }
  ],
  "techStackHighlights": ["string"],
  "freshersCtcRange": "string",
  "midLevelCtcRange": "string",
  "seniorCtcRange": "string",
  "joiningBonus": "string",
  "stockOptions": "string"
}`;

  try {
    const result = await groundedModel.generateContent(prompt);
    const text = result.response.text();
    const cleanText = text.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(cleanText);
  } catch (error) {
    console.error('[Gemini Grounding Error]', error);
    return {}; // fallback
  }
}

/**
 * Generate comprehensive company report using Flash-Lite
 */
export async function generateCompanyReport(company, role, exaData, groundedFacts) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `You are a career intelligence analyst.
Generate a comprehensive company research report for a job seeker.

Company: ${company}
Target Role: ${role}

=== DATA FROM WEB (Exa Search) ===

INTERVIEW EXPERIENCES (${exaData.interviewExperiences.length} sources):
${exaData.interviewExperiences.map(r => `Source: ${r.domain}\n${r.text.substring(0, 800)}`).join('\n---\n')}

CULTURE & REVIEWS:
${exaData.cultureReviews.map(r => r.highlights.join(' ')).join('\n')}

TECH STACK:
${exaData.techStackData.map(r => r.highlights.join(' ')).join('\n')}

RECENT NEWS:
${exaData.recentNews.map(r => `${r.title}: ${r.highlights[0] || ''}`).join('\n')}

=== VERIFIED FACTS (Google Grounding) ===
${JSON.stringify(groundedFacts)}

=== YOUR TASK ===
Generate a structured report with all 6 sections.
For contradictions (e.g. 3 vs 4 rounds):
→ Use the most frequently mentioned value
→ Add a note: 'varies by team/role'
Be specific, factual, and actionable for the job seeker.

Return ONLY this JSON (no markdown backticks):
{
  "overview": {
    "companyName": "string",
    "industry": "string",
    "founded": "string",
    "headquarters": "string",
    "size": "string",
    "techStack": ["string"],
    "productDescription": "string",
    "latestNews": [
      { "headline": "string", "url": "string", "date": "string", "source": "string" }
    ]
  },
  "interviewProcess": {
    "totalRounds": 0,
    "rounds": [
      {
        "number": 0,
        "name": "string",
        "description": "string",
        "duration": "string",
        "focusArea": "string"
      }
    ],
    "avgTimelineWeeks": 0,
    "difficulty": "string",
    "difficultyRating": 0,
    "sourcedFrom": "string"
  },
  "commonQuestions": {
    "technical": [
      { "question": "string", "frequency": "high|medium|low", "topic": "string" }
    ],
    "behavioral": [
      { "question": "string", "frequency": "high|medium|low" }
    ],
    "systemDesign": [
      { "question": "string", "frequency": "high|medium|low" }
    ]
  },
  "culture": {
    "overallRating": 0,
    "workLifeBalance": 0,
    "growthOpportunity": 0,
    "salaryRating": 0,
    "managementRating": 0,
    "pros": ["string"],
    "cons": ["string"],
    "idealFor": "string",
    "notIdealFor": "string",
    "reviewCount": 0,
    "reviewSource": "string"
  },
  "salary": {
    "role": "string",
    "fresher": { "min": "string", "max": "string", "median": "string" },
    "midLevel": { "min": "string", "max": "string", "median": "string" },
    "senior": { "min": "string", "max": "string", "median": "string" },
    "joiningBonus": "string",
    "stockOptions": "string",
    "otherBenefits": ["string"],
    "dataSource": "string",
    "lastUpdated": "string"
  },
  "aiPrepTips": {
    "mustFocusAreas": [
      { "area": "string", "reason": "string", "specificTip": "string" }
    ],
    "companySpecificInsight": "string",
    "dosAndDonts": { "dos": ["string"], "donts": ["string"] },
    "practiceQuestions": ["string"],
    "estimatedPrepWeeks": 0,
    "roadmapTopicsToAdd": ["string"]
  },
  "dataSources": ["string"],
  "dataFreshness": "string",
  "confidenceScore": 0
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    const cleanText = text.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(cleanText);
  } catch (error) {
    console.error('[Gemini Company Report Error]', error);
    throw error;
  }
}

/**
 * Generate side-by-side comparison report
 */
export async function generateCompareReport(report1, report2, role) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `You are an expert career analyst. Compare these two companies IN EXTREME DEPTH for a "${role}" candidate.

=== COMPANY 1: ${report1.overview?.companyName} ===
Overview: ${JSON.stringify(report1.overview)}
Interview: ${JSON.stringify(report1.interviewProcess)}
Culture: ${JSON.stringify(report1.culture)}
Salary: ${JSON.stringify(report1.salary)}
Prep Tips: ${JSON.stringify(report1.aiPrepTips)}

=== COMPANY 2: ${report2.overview?.companyName} ===
Overview: ${JSON.stringify(report2.overview)}
Interview: ${JSON.stringify(report2.interviewProcess)}
Culture: ${JSON.stringify(report2.culture)}
Salary: ${JSON.stringify(report2.salary)}
Prep Tips: ${JSON.stringify(report2.aiPrepTips)}

INSTRUCTIONS:
- Be EXTREMELY SPECIFIC. Use exact numbers, salary ranges, tech stacks, interview round counts.
- Do NOT be generic. Every value should contain a concrete data point.
- The "overallVerdict" should be 2-3 sentences, opinionated, and reference the role.
- For the comparisonTable, provide at LEAST 8 rich categories.
- For each "company1Value" and "company2Value", include a SPECIFIC metric or tag (e.g., "₹32L-48L CTC", "4.5/5 Glassdoor", "5 Rounds, ~6 weeks", "React, Go, K8s").
- The "winner" field should be "1", "2", or "tie".
- Provide "detailedAnalysis" as a paragraph explaining WHY one is better in that category.

Return ONLY this JSON (no markdown backticks):
{
  "comparisonTable": [
    {
      "category": "Culture & Work Environment",
      "icon": "diversity_3",
      "company1Value": "specific rating or tag",
      "company2Value": "specific rating or tag",
      "winner": "1|2|tie",
      "winnerReason": "one-liner reason",
      "detailedAnalysis": "2-3 sentences with specifics"
    },
    {
      "category": "Salary & Compensation",
      "icon": "payments",
      "company1Value": "exact range",
      "company2Value": "exact range",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    },
    {
      "category": "Tech Stack & Innovation",
      "icon": "terminal",
      "company1Value": "key technologies",
      "company2Value": "key technologies",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    },
    {
      "category": "Interview Difficulty",
      "icon": "psychology_alt",
      "company1Value": "difficulty + rounds",
      "company2Value": "difficulty + rounds",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    },
    {
      "category": "Work-Life Balance",
      "icon": "balance",
      "company1Value": "rating or tag",
      "company2Value": "rating or tag",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    },
    {
      "category": "Career Growth Trajectory",
      "icon": "trending_up",
      "company1Value": "growth path summary",
      "company2Value": "growth path summary",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    },
    {
      "category": "Market Position & Stability",
      "icon": "shield",
      "company1Value": "market tag",
      "company2Value": "market tag",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    },
    {
      "category": "Learning & Development",
      "icon": "school",
      "company1Value": "learning opportunities",
      "company2Value": "learning opportunities",
      "winner": "1|2|tie",
      "winnerReason": "one-liner",
      "detailedAnalysis": "2-3 sentences"
    }
  ],
  "overallVerdict": "2-3 sentence opinionated verdict referencing the specific role",
  "scorecard": {
    "company1Wins": 0,
    "company2Wins": 0,
    "ties": 0
  },
  "recommendFor": {
    "fresher": "Which company and WHY (1-2 sentences)",
    "experienced": "Which company and WHY (1-2 sentences)",
    "workLifeBalance": "Which company (1 sentence)",
    "highCTC": "Which company (1 sentence)",
    "careerGrowth": "Which company (1 sentence)"
  },
  "redFlags": {
    "company1": ["specific red flag 1", "specific red flag 2"],
    "company2": ["specific red flag 1", "specific red flag 2"]
  },
  "bottomLine": "One punchy sentence summarizing the entire comparison"
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    const cleanText = text.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(cleanText);
  } catch (error) {
    console.error('[Gemini Compare Report Error]', error);
    throw error;
  }
}

/**
 * Extract personalization hooks from person profile data
 */
export async function extractPersonalizationHooks(profile, recipientName, recipientRole, company) {
  const model = genAI.getGenerativeModel({ model: "gemini-3.1-flash-lite-preview", generationConfig: { responseMimeType: "application/json" } });

  const rawText = profile.rawLinkedInText || (profile.personSnippets ? profile.personSnippets.join('\n') : '');
  const newsText = profile.companyNews ? profile.companyNews.join('\n') : '';

  const prompt = `You extract personalization hooks for cold outreach messages.

Data fetched about ${recipientName} (${recipientRole} at ${company}):

${rawText}

Company recent news:
${newsText}

Extract the BEST personalization hooks — specific, genuine, non-creepy things to mention in a cold message.

Rules:
1. Only use information explicitly in the data — never invent
2. Pick max 4 hooks (quality over quantity)
3. Rank by how natural they feel in a message
4. Company news > career history > skills (for opening hooks)
5. If no good personal data -> use only company news

Return ONLY this JSON:
{
  "hooks": [
    {
      "type": "recent_post|career_history|company_news|shared_interest|achievement",
      "content": "the actual detail to reference",
      "usageHint": "how to naturally weave into message",
      "strength": "strong|medium|weak"
    }
  ],
  "companyContext": "1 sentence about company right now",
  "personalDataAvailable": boolean,
  "suggestedOpeningAngle": "best hook to start with"
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('[Gemini Hook Extraction Error]', error);
    return null;
  }
}

/**
 * Evaluate and score outreach messages
 */
// ─── JD TO RESUME KEY POINTS FUNCTIONS ──────────────────────────────────────

/**
 * Step 1: Analyze a Job Description and extract structured data
 */
export async function analyzeJobDescription(jdText) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `You are an expert job description analyst and career coach.
Analyze this job description and extract structured data.

Job Description:
${jdText.substring(0, 4000)}

Return ONLY this JSON:
{
  "detectedRole": "string (e.g. 'Full Stack Developer')",
  "companyType": "startup|product|service|mnc|unknown",
  "experienceRequired": "string (e.g. '1-3 years' or 'Fresher')",
  "keyTechnicalSkills": ["max 15 must-have skills from JD"],
  "toolsRequired": ["tools, platforms mentioned: Docker, AWS, Git etc."],
  "softSkillsMentioned": ["soft skills from JD"],
  "projectDomains": ["domains relevant to this role: e.g. 'e-commerce', 'fintech', 'social app'"],
  "keyResponsibilities": ["top 5 job responsibilities"],
  "niceToHaveSkills": ["optional/preferred skills"],
  "seniorityLevel": "fresher|junior|mid|senior",
  "focusAreas": ["top 3 most important areas from JD"]
}`;

  try {
    const response = await model.generateContent(prompt);
    let rawContent = response.response.text().trim();
    rawContent = rawContent.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(rawContent);
  } catch (error) {
    console.error('[Gemini Error - analyzeJobDescription]', error.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Step 3 (parallel): Generate skills list and experience bullets
 */
export async function generateSkillsAndBullets(jdAnalysis, userInfo, sectionsRequested) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `Generate resume content for a job seeker.

=== JOB REQUIREMENTS ===
Role: ${jdAnalysis.detectedRole}
Required Skills: ${(jdAnalysis.keyTechnicalSkills || []).join(', ')}
Tools: ${(jdAnalysis.toolsRequired || []).join(', ')}
Soft Skills Needed: ${(jdAnalysis.softSkillsMentioned || []).join(', ')}
Responsibilities: ${(jdAnalysis.keyResponsibilities || []).join(', ')}

=== CANDIDATE PROFILE ===
Experience Level: ${userInfo.experienceLevel}
Current Skills: ${(userInfo.existingSkills || []).join(', ')}
Years of Experience: ${userInfo.yearsOfExp}

=== GENERATE ONLY THESE SECTIONS ===
${sectionsRequested.join(', ')}

=== RULES ===
1. Skills:
   - Technical: Only include skills from JD + user already knows
   - Mark each as: 'matched' (user has it) or 'suggested' (from JD, new to user)
   - Suggested skills: only include if realistic to add to resume
   - Max 12 technical, 8 tools, 6 soft skills

2. Experience Bullets (if requested):
   - Write 5 strong action-verb bullets
   - Format: 'Verb + What + Impact metric'
   - Use numbers/percentages where possible
   - Tailor to the JD responsibilities
   - For fresher: frame as internship/project experience

Return ONLY this JSON:
{
  "skills": {
    "technical": [
      { "name": "string", "status": "matched|suggested" }
    ],
    "tools": [
      { "name": "string", "status": "matched|suggested" }
    ],
    "soft": ["string"]
  },
  "experienceBullets": ["5 bullets, empty array if not requested"]
}`;

  try {
    const response = await model.generateContent(prompt);
    let rawContent = response.response.text().trim();
    rawContent = rawContent.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(rawContent);
  } catch (error) {
    console.error('[Gemini Error - generateSkillsAndBullets]', error.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

/**
 * Fallback: Generate summary and projects via Gemini when Cerebras fails
 */
export async function generateSummaryAndProjectsFallback(jdAnalysis, userInfo, sectionsRequested) {
  if (!model) throw new Error('AI_UNAVAILABLE');

  const prompt = `Generate resume content for a job seeker applying for:
Role: ${jdAnalysis.detectedRole}
Company Type: ${jdAnalysis.companyType}
Candidate: ${userInfo.experienceLevel}, ${userInfo.yearsOfExp} experience
Their skills: ${(userInfo.existingSkills || []).join(', ')}
JD focus areas: ${(jdAnalysis.focusAreas || []).join(', ')}
JD domains: ${(jdAnalysis.projectDomains || []).join(', ')}
JD tech requirements: ${(jdAnalysis.keyTechnicalSkills || []).slice(0, 8).join(', ')}
Seniority: ${jdAnalysis.seniorityLevel}

Generate:
${sectionsRequested.includes('summary') ? '1. Professional Summary (3-4 sentences. If Fresher, focus on academics/projects and DO NOT write "0 years experience". If experienced, mention years of experience. No clichés)' : ''}
${sectionsRequested.includes('objective') && jdAnalysis.seniorityLevel === 'fresher' ? '2. Objective Statement (2 sentences for fresher)' : ''}
${sectionsRequested.includes('projects') ? '3. Three realistic resume projects with impact metrics' : ''}

Return ONLY this JSON:
{
  "summary": "string or null",
  "objective": "string or null",
  "projects": [
    {
      "name": "string",
      "tagline": "string",
      "description": "string",
      "techStack": ["string"],
      "bullets": ["3 impact-driven bullet points"],
      "domain": "string",
      "difficulty": "beginner|intermediate|advanced",
      "liveUrl": null,
      "githubUrl": null
    }
  ]
}`;

  try {
    const response = await model.generateContent(prompt);
    let rawContent = response.response.text().trim();
    rawContent = rawContent.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    return JSON.parse(rawContent);
  } catch (error) {
    console.error('[Gemini Fallback Error - generateSummaryAndProjects]', error.message);
    throw new Error('AI_UNAVAILABLE');
  }
}

export async function scoreMessageQuality(messages, messageType, goal) {
  const model = genAI.getGenerativeModel({ model: "gemini-3.1-flash-lite-preview", generationConfig: { responseMimeType: "application/json" } });

  const messagesText = messages.map((m, i) => `VERSION ${i+1}:\n${m}`).join('\n\n---\n\n');

  const prompt = `Evaluate these cold outreach messages for a job seeker.

Message Type: ${messageType}
Goal: ${goal}

Messages to evaluate:
${messagesText}

For each message, score on these dimensions (0-100):
1. personalization: Is it specific? Does it feel written for this person?
2. clarity: Is the goal clear? Is it easy to read?
3. callToAction: Is the ask specific and easy to respond to?
4. desperationLevel: Lower = better. Avoid needy/begging tone.
5. spamTriggers: Common spam phrases that hurt open rates.

Also identify:
- spamPhrases: exact phrases that are spam triggers
- suggestions: 2-3 specific improvements
- overallScore: weighted average (personalization 30%, clarity 25%, CTA 25%, low-desperation 20%)
- bestVersion: which is best (1, 2, or 3) + why

Return ONLY this JSON:
{
  "scores": [
    {
      "version": 1,
      "personalization": number,
      "clarity": number,
      "callToAction": number,
      "desperationLevel": number,
      "overallScore": number,
      "spamPhrases": ["string"],
      "suggestions": ["string"],
      "wordCount": number,
      "readingTimeSeconds": number
    }
  ],
  "bestVersion": number,
  "bestVersionReason": "string",
  "globalSuggestions": ["string"]
}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    return JSON.parse(text);
  } catch (error) {
    console.error('[Gemini Quality Score Error]', error);
    return null;
  }
}
